PacilFlix/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('authentication.urls')),
    path('admin/', admin.site.urls),
    path('kontributor/', include('kontributor.urls')),
    path('langganan/', include('langganan.urls')),
    path('tayangan/', include('trailer.urls')),
]

authentication/urls.py
from django.urls import path

from authentication.views import (form_register, login, login_register, logout,
                                  register, test)

app_name = 'authentication'

urlpatterns = [
    path('test/', test, name='test'),
    path('', login_register, name='login-register'),
    path('form-register/', form_register, name='form-register'),
    path('form-login/', login, name='form-login'),
    path('logout', logout, name='logout'),
    path('register', register, name='register')
]

trailer/urls.py
from django.urls import path
from . import views

app_name = 'trailer'

urlpatterns = [
    path('', views.trailer_list, name='trailer_list'),
    path('search/', views.search_trailer, name='search_trailer'),
    path('film/<str:film_id>', views.film_detail, name='film_detail'),
    path('series/<str:series_id>', views.series_detail, name='series_detail'),
    path('episode/<str:id>/<str:sub_judul>', views.episode_detail, name='episode_detail'),
    path('add-ulasan/', views.add_ulasan, name='add_ulasan'),
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
import pycountry
from django.db import connection
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        with connection.cursor() as cursor:
            cursor.execute((f"SELECT username, negara_asal FROM PENGGUNA WHERE username = '{username}' AND password = '{password}'"))
            data = cursor.fetchall()
        if len(data) != 0:
            username = data[0][0]
            negara_asal = data[0][1]

            request.session['username'] = username
            request.session['negara_asal'] = negara_asal
            request.session['is_authenticated'] = True

            return HttpResponseRedirect(reverse('trailer:trailer_list'))
        else:
            return render(request, 'form_login.html', {'login_failed': True})
    else:
        if request.session.get('is_authenticated'):
            return HttpResponseRedirect(reverse('trailer:trailer_list'))
        return render(request, 'form_login.html')

@csrf_exempt
def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        country = request.POST.get('country')
        error_message = None
        error = False
        try:
            with connection.cursor() as cursor:
                cursor.execute("INSERT INTO PENGGUNA (username, password, negara_asal) VALUES (%s, %s, %s)", [username, password, country])
        except Exception as e:
            error_message = str(e)
            error = True
            print(error_message)
        if error_message:
            return render(request, 'form_register.html', {'error':error, 'error_message': error_message})
        else:
            return render(request, 'form_login.html')
    else:
        return render(request, 'form_register.html')

def login_register(request):
    if request.session.get('is_authenticated'):
        return HttpResponseRedirect(reverse('trailer:trailer_list'))
    return render(request, 'login_register.html')

def form_register(request):
    if request.session.get('is_authenticated'):
        return HttpResponseRedirect(reverse('trailer:trailer_list'))
    return render(request, 'form_register.html')

def test(request):
    return render(request, "test.html")

def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('authentication:login-register'))

authentication/templates/form_login.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5 shadow">
                <div class="card-body">
                    <h2 class="card-title text-center">LOGIN FORM</h2>

                    <form method="POST" action="{% url 'authentication:form-login' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" class="form-control" id="username" name="username">
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" class="form-control" id="password" name="password">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">LOGIN</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    body {
        background-image: url('https://user-images.githubusercontent.com/16425113/129554147-6ac7ba51-43e7-4c8e-ba77-e646a3ef6b12.jpg');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        height: 100vh;
    }
</style>

{% if login_failed %}
<script>
    alert('Login failed: Username or password is incorrect.');
</script>
{% endif %}

{% endblock %}

authentication/templates/login_register.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid d-flex align-items-center vh-100">
    <div class="row justify-content-center w-100">
        <div class="col-md-10">
            <div class="text-center">
                <div>
                    <h1 class="h1 font-weight-bold text-light">Unlimited movies, TV shows, and more</h1>
                    <p class="h3 lead text-light">Tonton dimanapun, kapanpun.</p>
                    <div class="mt-4">
                        <a class="btn btn-danger btn-lg ml-2" href="{% url 'authentication:form-register' %}" role="button">Register</a>
                        <a class="btn btn-secondary btn-lg ml-2" href="{% url 'authentication:form-login' %}" role="button">Login</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    body {
        background-image: url('https://user-images.githubusercontent.com/16425113/129554147-6ac7ba51-43e7-4c8e-ba77-e646a3ef6b12.jpg');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        height: 100vh;
        position: relative;
    }

    /* Black gradient overlay */
    body::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3));
    }
</style>
{% endblock %}