PacilFlix/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('authentication.urls')),
    path('admin/', admin.site.urls),
    path('kontributor/', include('kontributor.urls')),
    path('langganan/', include('langganan.urls')),
    path('tayangan/', include('trailer.urls')),
]

trailer/urls.py
from django.urls import path
from . import views

app_name = 'trailer'

urlpatterns = [
    path('', views.trailer_list, name='trailer_list'),
    path('search/', views.search_trailer, name='search_trailer'),
    path('film/<str:film_id>', views.film_detail, name='film_detail'),
    path('series/<str:series_id>', views.series_detail, name='series_detail'),
    path('episode/<str:id>/<str:sub_judul>', views.episode_detail, name='episode_detail'),
    path('add-ulasan/', views.add_ulasan, name='add_ulasan'),
]

trailer/views.py
from django.http import Http404, HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.db import InternalError, connection
from urllib.parse import quote

def trailer_list(request):   
    top_10_selection = 'global'

    # ambil data negara pengguna jika pengguna sudah login
    if request.session.get('is_authenticated'):
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT
                    negara_asal
                FROM
                    pengguna
                WHERE
                    username = %s
            """, [request.session.get('username')])
            user_country = cursor.fetchone()[0]

    if request.method == 'POST' and request.session.get('is_authenticated'):
        top_10_selection = request.POST.get('top_10_selection', 'global')

    base_query = """
        WITH tayangan_durasi AS (
            SELECT
                t.id AS id_tayangan,
                t.judul,
                t.sinopsis AS sinopsis_trailer,
                t.url_video_trailer AS trailer_url,
                t.release_date_trailer,
                CASE
                    WHEN f.id_tayangan IS NOT NULL THEN f.durasi_film
                    WHEN e.id_series IS NOT NULL THEN e.durasi
                    ELSE 0
                END AS durasi_tayangan,
                EXTRACT(EPOCH FROM (r.end_date_time - r.start_date_time)) / 60 AS durasi_nonton
            FROM
                tayangan t
            LEFT JOIN
                film f ON t.id = f.id_tayangan
            LEFT JOIN
                episode e ON t.id = e.id_series
            LEFT JOIN
                riwayat_nonton r ON t.id = r.id_tayangan
            WHERE
                r.start_date_time >= CURRENT_DATE - INTERVAL '7 days'
    """

    if top_10_selection == 'asal_negara' and request.session.get('is_authenticated'):
        where_clause = f"AND t.asal_negara = '{user_country}'"
    else:
        where_clause = ""

    final_query = base_query + where_clause + """
        ),
        view_count AS (
            SELECT
                id_tayangan,
                judul,
                sinopsis_trailer,
                trailer_url,
                release_date_trailer,
                COUNT(*) AS view_count
            FROM
                tayangan_durasi
            WHERE
                durasi_nonton >= 0.7 * durasi_tayangan
            GROUP BY
                id_tayangan, judul, sinopsis_trailer, trailer_url, release_date_trailer
        )
        SELECT
            id_tayangan,
            judul,
            sinopsis_trailer,
            trailer_url,
            release_date_trailer,
            view_count
        FROM
            view_count
        ORDER BY
            view_count DESC
        LIMIT 10;
    """

    with connection.cursor() as cursor:
        cursor.execute(final_query)
        top_10_data = cursor.fetchall()
    
    # Fetch film data from database
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT
                t.id,
                t.judul,
                t.sinopsis,
                t.asal_negara,
                t.url_video_trailer AS trailer_url,
                t.release_date_trailer AS release_date
            FROM
                tayangan t
            INNER JOIN
                film f ON t.id = f.id_tayangan
        """)
        film_data = cursor.fetchall()

    # Fetch series data from database
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT
                t.id,
                t.judul,
                t.sinopsis,
                t.asal_negara,
                t.url_video_trailer AS trailer_url,
                t.release_date_trailer AS release_date
            FROM
                tayangan t
            INNER JOIN
                series s ON t.id = s.id_tayangan
        """)
        series_data = cursor.fetchall()
                
    # Mapping data ke dictionary untuk dikirim ke template
    top_10 = [{'peringkat': i+1, 'judul': row[1], 'sinopsis': row[2], 'trailer_url': row[3],
               'release_date': row[4], 'view_count': row[5]} for i, row in enumerate(top_10_data)]
    
    films = [{'id': row[0], 'judul': row[1], 'sinopsis': row[2], 'asal_negara':row[3], 'trailer_url': row[4], 'release_date': row[5]} for row in film_data]
    series = [{'id': row[0], 'judul': row[1], 'sinopsis': row[2], 'asal_negara':row[3], 'trailer_url': row[4], 'release_date': row[5]} for row in series_data]
    
    context = {
        'top_10': top_10,
        'films': films,
        'series': series,
        'top_10_selection': top_10_selection
    }
    
    return render(request, 'daftar_tayangan.html', context)


def search_trailer(request):
    search_query = request.GET.get('search', '')

    # Jika tidak ada query pencarian, kembalikan template dengan pesan bahwa tidak ada hasil
    if not search_query:
        return render(request, 'search_tayangan.html', {'error': 'Masukkan judul tayangan untuk mencari.'})

    # Pencarian dalam database untuk film dan series berdasarkan judul
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT
                t.id,
                t.judul,
                t.sinopsis,
                t.url_video_trailer AS trailer_url,
                t.release_date_trailer AS release_date
            FROM
                tayangan t
            WHERE
                t.judul ILIKE %s
        """, [f'%{search_query}%'])
        search_results = cursor.fetchall()

    # Menentukan tipe tayangan (film atau series) dari hasil pencarian
    results = []
    for row in search_results:
        # Ambil ID tayangan dari hasil pencarian
        tayangan_id = row[0]
        
        # Periksa apakah tayangan tersebut adalah film atau series
        with connection.cursor() as inner_cursor:
            inner_cursor.execute("""
                SELECT
                    CASE
                        WHEN f.id_tayangan IS NOT NULL THEN 'Film'
                        WHEN s.id_tayangan IS NOT NULL THEN 'Series'
                        ELSE 'Unknown'
                    END AS tipe_tayangan
                FROM
                    tayangan t
                LEFT JOIN
                    film f ON t.id = f.id_tayangan
                LEFT JOIN
                    series s ON t.id = s.id_tayangan
                WHERE
                    t.id = %s
            """, [tayangan_id])
            tipe_tayangan = inner_cursor.fetchone()[0]
        
        # Tambahkan hasil pencarian beserta tipe tayangannya ke dalam list results
        results.append({
            'judul': row[1],
            'sinopsis': row[2],
            'trailer_url': row[3],
            'release_date': row[4],
            'tipe_tayangan': tipe_tayangan
        })

    context = {
        'search_query': search_query,
        'results': results,
    }

    return render(request, 'search_tayangan.html', context)

@csrf_exempt
def film_detail(request, film_id):
    if not request.session.get('is_authenticated'):
        return redirect(reverse('authentication:form-login'))
    
    # Ambil data film dari database dengan menggabungkan tabel Tayangan dan Film
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT
                t.judul,
                t.sinopsis,
                f.durasi_film,
                t.url_video_trailer,
                t.release_date_trailer,
                t.asal_negara,
                COUNT(r.id_tayangan) AS total_views,
                COALESCE(AVG(u.rating), 0) AS average_rating
            FROM
                tayangan t
            LEFT JOIN
                film f ON t.id = f.id_tayangan
            LEFT JOIN
                riwayat_nonton r ON t.id = r.id_tayangan
            LEFT JOIN
                ulasan u ON t.id = u.id_tayangan
            WHERE
                t.id = %s
            GROUP BY
                t.id, f.id_tayangan;
        """, [film_id])
        film_data = cursor.fetchone()

        # Fetch reviews for the film
        cursor.execute("SELECT rating FROM ULASAN WHERE id_tayangan = %s", [film_id])
        ratings = cursor.fetchall()

        cursor.execute("""
            SELECT username, rating, deskripsi FROM ULASAN WHERE id_tayangan = %s ORDER BY timestamp DESC
        """, [film_id])
        reviews = cursor.fetchall()

        # Fetch genre data for the film
        cursor.execute("""
            SELECT genre FROM genre_tayangan WHERE id_tayangan = %s
        """, [film_id])
        genre_data = cursor.fetchall()

        # Fetch cast data for the film
        cursor.execute("""
            SELECT c.nama
            FROM contributors c
            INNER JOIN memainkan_tayangan mt ON c.id = mt.id_pemain
            WHERE mt.id_tayangan = %s
        """, [film_id])
        cast_data = cursor.fetchall()

        # Fetch writer data for the film
        cursor.execute("""
            SELECT c.nama
            FROM contributors c
            INNER JOIN menulis_skenario_tayangan ms ON c.id = ms.id_penulis_skenario
            WHERE ms.id_tayangan = %s
        """, [film_id])
        writer_data = cursor.fetchall()

        # Fetch director data for the film
        cursor.execute("""
            SELECT c.nama
            FROM contributors c
            INNER JOIN tayangan t ON c.id = t.id_sutradara
            WHERE t.id = %s
        """, [film_id])
        director_data = cursor.fetchall()

        # Calculate total_views (jumlah entri di tabel RIWAYAT_NONTON)
        cursor.execute("SELECT COUNT(*) FROM RIWAYAT_NONTON WHERE id_tayangan = %s", [film_id])
        total_views_data = cursor.fetchone()

    # Calculate total_views and average_rating
    total_views = total_views_data[0] if total_views_data else 0

trailer/templates/daftar_tayangan.html
{% extends 'base.html' %}
{% load custom_filter %}

{% block title %}Daftar Tayangan{% endblock %}

{% block content %}
<h1>DAFTAR TAYANGAN</h1>
<form class="form-inline mb-3" method="GET" action="{% url 'trailer:search_trailer' %}">
    <input class="form-control mr-sm-2" type="text" name="search" placeholder="Pencarian Tayangan berdasarkan judul" aria-label="Search">
    <button class="btn btn-dark my-2 my-sm-0" type="submit">Cari</button>
</form>

<div class="top-10">
    <h2>10 Tayangan Terbaik Minggu Ini</h2>
    {% if request.session.is_authenticated %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    <form method="POST" action="{% url 'trailer:trailer_list' %}">
                        {% csrf_token %}
                        <button class="btn {% if top_10_selection == 'global' %} btn-danger {% else %} btn-secondary {% endif %} mb-3 w-100" type="submit" name="top_10_selection" value="global">Top Global</button>
                    </form>
                </th>
                <th>
                    <form method="POST" action="{% url 'trailer:trailer_list' %}">
                        {% csrf_token %}
                        <button class="btn {% if top_10_selection == 'asal_negara' %} btn-danger {% else %} btn-secondary {% endif %} mb-3 w-100" type="submit" name="top_10_selection" value="asal_negara">Top Lokal</button>
                    </form>
                </th>
            </tr>
        </thead>
    {% else %}
    <form method="POST" action="{% url 'trailer:trailer_list' %}">
        {% csrf_token %}
        <button class="btn btn-danger mb-3 w-100" name="top_10_selection" disabled>Top Global</button>
    </form>
    {% endif %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Peringkat</th>
                <th>Judul</th>
                <th>Sinopsis</th>
                <th>Trailer URL</th>
                <th>Tanggal Rilis</th>
                <th>Total View 7 Hari Terakhir</th>
            </tr>
        </thead>
        <tbody>
            {% for tayangan in top_10 %}
            <tr>
                <td>{{ tayangan.peringkat }}</td>
                <td>{{ tayangan.judul }}</td>
                <td>{{ tayangan.sinopsis }}</td>
                <td>{{ tayangan.trailer_url }}</td>
                <td>{{ tayangan.release_date }}</td>
                <td>{{ tayangan.view_count }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="film">
    <h2>Film</h2>
    <div class="grid-wrapper">
        {% for film in films %}
        <div class="card" data-id="{{ film.id }}">
            <img src="http://img.youtube.com/vi/{{ film.trailer_url|youtube_id }}/hqdefault.jpg" class="card-img-top" alt="{{ film.judul }} thumbnail">
            <div class="card-body">
                <h5 class="card-title">{{ film.judul }}</h5>
                <p class="card-text">{{ film.sinopsis }}</p>
                <p class="card-text">{{ film.release_date }}</p>
                <a href="{{ film.trailer_url }}" class="btn btn-primary">Lihat Trailer</a>
                {% if request.session.is_authenticated %}
                <a href="{% url 'trailer:film_detail' film.id %}" class="btn btn-dark">Tayangan</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="series">
    <h2>Series</h2>
    <div class="grid-wrapper">
        {% for serie in series %}
        <div class="card" data-id="{{ serie.id }}">
            <img src="http://img.youtube.com/vi/{{ serie.trailer_url|youtube_id }}/hqdefault.jpg" class="card-img-top" alt="{{ serie.judul }} thumbnail">
            <div class="card-body">
                <h5 class="card-title">{{ serie.judul }}</h5>
                <p class="card-text">{{ serie.sinopsis }}</p>
                <p class="card-text">{{ serie.release_date }}</p>
                <a href="{{ series.trailer_url }}" class="btn btn-primary">Lihat Trailer</a>
                {% if request.session.is_authenticated %}
                <a href="{% url 'trailer:series_detail' serie.id %}" class="btn btn-dark">Tayangan</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<style>
    .grid-wrapper {
        display: grid;
        grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
        gap: 10px;
        padding: 20px;
    }

    .grid-wrapper .card {
        cursor: pointer;
        transition: transform 0.3s, width 0.3s;
    }

    .grid-wrapper .card:hover {
        transform: scale(1.1);
    }

    .grid-wrapper .card:hover .card-text {
        display: block;
    }

    .grid-wrapper .card .card-text {
        display: none;
    }

    .card-img-top {
        width: 100%;
        height: auto;
    }
</style>

{% endblock %}

trailer/templates/film_detail.html
{% extends 'base.html' %}
{% load custom_filter %}

{% block title %}Film Detail{% endblock %}

{% block content %}
<h1>Film Detail</h1>
<div class="film-detail">
    <div class="card">
        <img src="http://img.youtube.com/vi/{{ film.url_video_trailer|youtube_id }}/hqdefault.jpg" class="card-img-top" alt="{{ film.judul }} thumbnail">
        <div class="card-body">
            <h5 class="card-title">{{ film.judul }}</h5>
            <div class="slider">
                <form id="progressForm" action="" method="post">
                    {% csrf_token %}  
                    <input type="hidden" name="id" value="{{ film.id }}">
                    <input type="hidden" name="tipe" value="film">
                    <input type="hidden" name="durasi" value="{{ film.durasi_film }}">
                    <label for="progress" class="form-label"><b>Progress:</b></label>
                    <input type="range" class="form-range" name="progress" id="progress">
                </form>
              </div>
              <div class="btn-group" role="group">
                <button class="btn btn-primary mb-2" id="btnTonton" onclick="">Tonton</button>
            </div>
            <h2>
                <a href="">
                    <button class="btn btn-primary mb-2" id="btnUnduh" data-bs-toggle="modal" data-bs-target="#downloadModal" data-id= "{{ film.id }}">Unduh</button>
                </a>
            </h2>
            <h2>
                <button class="btn btn-primary mb-2" id="btnFavorit" data-bs-toggle="modal" data-bs-target="#favoriteListModal">Jadikan Favorit</button>
            </h2>
            <p class="card-text">{{ film.sinopsis }}</p>
            <p class="card-text">Durasi Film: {{ film.durasi_film }} menit</p>
            <p class="card-text">Tanggal Rilis: {{ film.release_date }}</p>
            <p class="card-text">Total View: {{ film.total_views }}</p>
            <p class="card-text">Rating Rata-Rata: {{ film.average_rating }}</p>
            <p class="card-text">URL Film: <a href="{{ film.url_video_trailer }}">Tonton Trailer</a></p>
            <h3>Genre:</h3>
            <ul>
                {% for genre in film.genre %}
                    <li>{{ genre }}</li>
                {% endfor %}
            </ul>
            <h3>Asal Negara: {{ film.asal_negara }}</h3>
            <h3>Pemain:</h3>
            <ul>
                {% for actor in film.pemain %}
                    <li>{{ actor }}</li>
                {% endfor %}
            </ul>
            <h3>Penulis Skenario:</h3>
            <ul>
                {% for writer in film.penulis_skenario %}
                    <li>{{ writer }}</li>
                {% endfor %}
            </ul>
            <h3>Sutradara:</h3>
            <ul>
                {% for director in film.sutradara %}
                    <li>{{ director }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="modal fade" id="favoriteListModal" tabindex="-1" aria-labelledby="favoriteListModalLabel" aria-hidden="true" data-bs-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="favoriteListModalLabelTitle">Modal Daftar Favorit</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <select class="form-select mb-3" id="dropdown-favorite">
                        <option value="select-daftar-favorit">Judul Daftar Favorit: </option>
                        {% for judul_daftar in list_daftar_favorit %}
                        <option value=""></option>
                        {% endfor %}
                    </select>
                </div>
                <div class="modal-footer d-flex justify-content-center">
                    <a id="link_add_favorite" href="#">
                        <button type="button" class="btn btn-primary" id="button_add_favorite" data-bs-dismiss="modal">Tambah</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal fade" id="downloadModal" tabindex="-1" aria-labelledby="downloadModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="downloadModalLabelTitle">Berhasil Ditambah ke Daftar Unduhan!</h1>
                </div>
                <div class="modal-body" id="downloadModalBody">
                    <p>
                    </p>
                </div>
                <div class="modal-footer">
                    <a href="" class="text-white hover:text-gray-300 me-2">
                        <button type="button" class="btn btn-primary mb-2">Daftar Unduhan</button>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bagian Ulasan -->
    <div class="row-md-4">
        <h2 class="title">Bagian Ulasan</h2>
        <div class="form-group">
            <form action="{% url 'trailer:add_ulasan' %}" method="post">
                {% csrf_token %}  
                <input type="hidden" name="id_tayangan" value="{{ film.id }}">
                <input type="hidden" name="tipe" value="film">
                <div class="row">
                    <div class="col-md-8">
                        <input type="text" class="form-control mb-2" id="inputUlasan" name="deskripsi" placeholder="Deskripsi Ulasan" maxlength="255" required>
                    </div>
                    <div class="col-md-2">
                        <input type="number" class="form-control mb-2" id="inputRating" name="rating" placeholder="Rating (1-10)" min="1" max="10" required>
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary mb-2" id="btnSubmit">Kirim Ulasan</button>
                    </div>
                </div>
            </form>
        </div>
        {% if messages %}
        <div class="message-container">
            <ul class="messages">
                {% for message in messages %}
                {% if 'ulasan' in message.tags %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endif %}
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <h5><b>Daftar Ulasan:</b></h5>
        <ul class="list-disc pl-4" id="daftarUlasan">
            {% for item in reviews %}
            <b>Username:</b> {{ item.username }}</br>
            <b>Rating:</b> {{ item.rating }}</br>
            <b>Deskripsi:</b> {{ item.deskripsi }}</br></br>
            {% empty %}
            <div class="empty">Belum ada ulasan</div>
            {% endfor %}
        </ul>
    </div>
</div>
<script>
    document.getElementById("btnSubmit").addEventListener("click", function() {
        var inputRating = document.getElementById("inputRating").value;
        if (isNaN(inputRating) || inputRating < 0 || inputRating > 10) {
            alert("Rating harus dalam rentang 0-10");
            return false;
        }
        console.log("Rating: " + inputRating);
    });
</script>
{% endblock %}

trailer/templates/search_tayangan.html
{% extends 'base.html' %}

{% block title %}Hasil Pencarian{% endblock %}

{% block content %}
<h1>Hasil Pencarian untuk "{{ search_query }}"</h1>
<form class="form-inline mb-3" method="GET" action="{% url 'trailer:search_trailer' %}">
    <input class="form-control mr-sm-2" type="text" name="search" value="{{ search_query }}" placeholder="Cari tayangan berdasarkan judul" aria-label="Search">
    <button class="btn btn-dark my-2 my-sm-0" type="submit">Cari</button>
</form>

{% if results %}
<h2>Hasil Pencarian</h2>
<div class="card shadow mt-3">
    <div class="card-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Judul</th>
                    <th scope="col">Sinopsis Trailer</th>
                    <th scope="col">URL Trailer</th>
                    <th scope="col">Tanggal Rilis Trailer</th>
                    {% if user.is_authenticated %}
                    <th scope="col">Tayangan</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for result in results %}
                <tr>
                    <td>{{ result.judul }}</td>
                    <td>{{ result.sinopsis }}</td>
                    <td><a href="{{ result.trailer_url }}" target="_blank">{{ result.trailer_url }}</a></td>
                    <td>{{ result.release_date }}</td>
                    {% if request.session.is_authenticated %}
                    <!-- tentukan apakah film/series -->
                    {% if result.tipe_tayangan == 'film' %}
                    <td><a href="{% url 'trailer:film_detail' %}" class="btn btn-dark">Tayangan</a></td>
                    {% else %}
                    <td><a href="{% url 'trailer:series_detail' %}" class="btn btn-dark">Tayangan</a></td>
                    {% endif %}
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% else %}
<p class="mt-3">Tidak ada tayangan yang ditemukan untuk "{{ search_query }}".</p>
{% endif %}
{% endblock %}

trailer/templates/series_detail.html
{% extends 'base.html' %}

{% block title %}Series Detail{% endblock %}

{% block content %}
<h1>Series Detail</h1>
<div class="series-detail">
    <div class="card">
        <div class="card-body">
            <h2>Judul: {{ series.judul }}</h2>
            <h3>Episode:</h3>
            {% if series.episodes %}
                <div class="card">
                    <div class="card-body">
                        <ul>
                            {% for episode in series.episodes %}
                            <a href="{% url 'trailer:episode_detail' id=series.id sub_judul=episode.title %}"class="list-group-item">>{{ episode.title }}</a>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% else %}
                <p>Currently not available</p>
            {% endif %}
            <h2>
                <button class="btn btn-primary mb-2" id="btnFavorit" data-bs-toggle="modal" data-bs-target="#favoriteListModal" data-judul_tayangan="">Jadikan Favorit</button>
            </h2>
            <h2>
                <a href=""><button class="btn btn-primary mb-2" id="btnUnduh" data-bs-toggle="modal" data-bs-target="#downloadModal" data-id= "{{ series.id }}">Unduh</button></a>
            </h2>
            <p>Sinopsis: {{ series.sinopsis }}</p>
            <p>Total View: {{ series.total_views }}</p>
            <p>Rating Rata-Rata: {{ series.average_rating }}</p>
            <h3>Genre:</h3>
            <ul>
                {% for genre in series.genre %}
                    <li>{{ genre }}</li>
                {% endfor %}
            </ul>
            <h3>Asal Negara: {{ series.asal_negara }}</h3>
            <h3>Pemain:</h3>
            <ul>
                {% for actor in series.pemain %}
                    <li>{{ actor }}</li>
                {% endfor %}
            </ul>
            <h3>Penulis Skenario:</h3>
            <ul>
                {% for writer in series.penulis_skenario %}
                    <li>{{ writer }}</li>
                {% endfor %}
            </ul>
            <h3>Sutradara:</h3>
            <ul>
                {% for director in series.sutradara %}
                    <li>{{ director }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <!-- Bagian Ulasan -->
    <div class="row-md-4">
        <h2 class="title">Bagian Ulasan</h2>
        <div class="form-group">
            <form action="{% url 'trailer:add_ulasan' %}" method="post">
                {% csrf_token %}  
                <input type="hidden" name="id_tayangan" value="{{ series.id }}">
                <input type="hidden" name="tipe" value="series">
                <div class="row">
                    <div class="col-md-8">
                        <input type="text" class="form-control mb-2" id="inputUlasan" name="deskripsi" placeholder="Deskripsi Ulasan" maxlength="255" required>
                    </div>
                    <div class="col-md-2">
                        <input type="number" class="form-control mb-2" id="inputRating" name="rating" placeholder="Rating (1-10)" min="1" max="10" required>
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary mb-2" id="btnSubmit">Kirim Ulasan</button>
                    </div>
                </div>
            </form>
        </div>
        {% if messages %}
        <div class="message-container">
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <h5><b>Daftar Ulasan:</b></h5>
        <ul class="list-disc pl-4" id="daftarUlasan">
            {% for item in reviews %}
            <b>Username:</b> {{ item.username }}</br>
            <b>Rating:</b> {{ item.rating }}</br>
            <b>Deskripsi:</b> {{ item.deskripsi }}</br></br>
            {% empty %}
            <div class="empty">Belum ada ulasan</div>
            {% endfor %}
        </ul>
    </div>
</div>
<script>
    document.getElementById("btnSubmit").addEventListener("click", function() {
        var inputRating = document.getElementById("inputRating").value;
        if (isNaN(inputRating) || inputRating < 0 || inputRating > 10) {
            alert("Rating harus dalam rentang 0-10");
            return false;
        }
        console.log("Rating: " + inputRating);
    });
</script>
{% endblock %}